export const signalMessages = {
  "zh-CN": {
    overview: "选择股票池与策略提交手动扫描，管理定时任务并查看已发布报告。", searchBasket: "搜索股票池", emptyPlans: "暂无定时任务。创建后可在这里管理和启停。", emptyReports: "暂无已发布的信号报告。",
    schemaMissing: "信号中心数据库表尚未部署，请先完成数据库预检和授权建表。", rendering: "导出文件",
    language: "报告语言", title:"信号中心", manual:"手动扫描", scheduled:"定时任务", name:"名称", market:"市场", basket:"股票池", strategies:"策略实例", session:"交易日（留空使用最新就绪日）", scan:"开始扫描", scanQueued:"扫描已提交，后台将继续处理。", save:"保存定时任务", recipients:"通知邮箱（逗号分隔）", retention:"保留交易日数", create:"创建定时任务", reports:"信号报告", view:"查看", status:"状态", signals:"信号", stocks:"股票", coverage:"覆盖", date:"交易日", enable:"启用", disable:"停用", edit:"编辑", empty:"暂无记录", loading:"加载中…", refresh:"刷新", previous:"上一页", next:"下一页", expired:"报告已过期", report:"信号观察报告", search:"搜索股票", all:"全部策略", passed:"通过筛选", audit:"全部审计记录", filtered:"未通过筛选", locate:"定位本信号", older:"加载更早行情", layers:"显示图层", enlarge:"放大", evidence:"信号证据", raw:"原始证据", export:"导出", send:"发送邮件", retry:"重试", expires:"到期时间", calendar:"等待完整交易日历", back:"返回信号中心", snapshot:"不可变快照", missing:"缺失", manualHint:"提交后由后台继续处理；此页面不显示扫描记录、进度或结果。", scheduledHint:"启用后：当日数据就绪 → 扫描 → 报告 → 邮件。停机恢复只处理最新就绪日。", scannable:"可扫描", unsupported:"不可扫描", selected:"已选择", remaining:"到达快照边界，不读取最新行情", previousSignal:"上一条信号", nextSignal:"下一条信号", dimensions:"观测值", thresholds:"策略阈值", grouped:"按股票", byStrategy:"按策略" },
  "en-US": {
    overview: "Choose a stock basket and strategies to submit manual scans, manage scheduled tasks, and review published reports.", searchBasket: "Search stock baskets", emptyPlans: "No scheduled tasks yet. Create a task to manage it here.", emptyReports: "No published signal reports yet.",
    schemaMissing: "Signal Center schema is not installed. Preflight and authorize schema installation first.", rendering: "Export rendering",
    language: "Report language", title:"Signal Center", manual:"Manual scan", scheduled:"Scheduled tasks", name:"Name", market:"Market", basket:"Stock basket", strategies:"Strategy instances", session:"Session (blank: latest ready)", scan:"Start scan", scanQueued:"Scan submitted. Processing will continue in the background.", save:"Save scheduled task", recipients:"Email recipients (comma separated)", retention:"Retention sessions", create:"Create scheduled task", reports:"Signal reports", view:"Open", status:"Status", signals:"Observations", stocks:"Instruments", coverage:"Coverage", date:"Session", enable:"Enable", disable:"Pause", edit:"Edit", empty:"No records", loading:"Loading…", refresh:"Refresh", previous:"Previous page", next:"Next page", expired:"Report expired", report:"Signal observation report", search:"Search symbols", all:"All strategies", passed:"Passed filters", audit:"All observations", filtered:"Filtered out", locate:"Locate signal", older:"Load earlier bars", layers:"Show layers", enlarge:"Expand", evidence:"Signal evidence", raw:"Raw evidence", export:"Export", send:"Send email", retry:"Retry", expires:"Expires", calendar:"Waiting for complete calendar", back:"Back to Signal Center", snapshot:"Immutable snapshot", missing:"Missing", manualHint:"Processing continues in the background after submission; this page does not show scan history, progress, or results.", scheduledHint:"When enabled: data ready → scan → report → email. Recovery processes only the latest ready session.", scannable:"Scannable", unsupported:"Not scannable", selected:"Selected", remaining:"Snapshot boundary reached; current quotes are not loaded", previousSignal:"Previous signal", nextSignal:"Next signal", dimensions:"Observed values", thresholds:"Strategy thresholds", grouped:"By instrument", byStrategy:"By strategy" },
};

const statusLabels: Record<"zh-CN"|"en-US",Record<string,string>> = {
  "zh-CN": {
    schemaMissing: "信号中心数据库表尚未部署，请先完成数据库预检和授权建表。", rendering: "导出文件",queued:"排队中",running:"运行中",completed:"已完成",partial:"覆盖不完整",failed:"失败",sending:"发送中",sent:"已发送",unknown:"投递结果不确定",expired:"已过期",enabled:"已启用",disabled:"已停用",not_sent:"未发送"},
  "en-US": {
    schemaMissing: "Signal Center schema is not installed. Preflight and authorize schema installation first.", rendering: "Export rendering",queued:"Queued",running:"Running",completed:"Completed",partial:"Incomplete coverage",failed:"Failed",sending:"Sending",sent:"Sent",unknown:"Delivery uncertain",expired:"Expired",enabled:"Enabled",disabled:"Paused",not_sent:"Not sent"},
};
export function signalStatus(status:string,locale:"zh-CN"|"en-US"):string {return statusLabels[locale][status]||status;}
