import type { CandleBarOut } from "./quote";
export type Json = null | string | number | boolean | Json[] | { [key: string]: Json };
export interface Page<T> { items: T[]; total: number }
export interface Coverage { expected: number; evaluated: number; not_evaluated: number; reasons: Record<string, number> }
export interface ScanInput { name: string; market: "US" | "CN"; basket_id: string; strategy_ids: string[]; session_date: string | null }
export interface PlanInput extends ScanInput { language: "zh-CN" | "en-US"; recipients: string[]; retention_sessions: number; enabled: boolean }
export interface Plan extends Omit<PlanInput, "strategy_ids"> { id: string; strategies: { strategy_id: string; strategy_type: string; name: string; version: number }[] }
export interface Scan { id: string; name: string; status: string; market: string; session_date: string; error: string | null; coverage: Record<string,Coverage>; plan_id: string | null; created_at: string }
export interface Observation { id: string; strategy_run_id: string; instrument_id: number; symbol_as_of: string; session_date: string; strategy_name: string; strategy_type: string; strategy_version: number; event_type: string; event_kind: string; direction: string | null; passes_signal_filters: boolean; strategy_rank: number | null; strength: { score: number } | null; reason?: string; evidence: Record<string,Json> }
export interface ReportSummary { name: string; market: string; session_date: string; observation_count: number; instrument_count: number; strategy_count: number; completed_strategies: number; status: string }
export interface Report { render_status: string | null; render_error: string | null; error: string | null; id: string; scan_id: string; status: string; language: string; summary: ReportSummary; published_at: string | null; expires_at: string | null; retention_reason: string | null; expired_at: string | null; render_errors: Record<string,string>; formats?: string[]; document?: { strategy_sections?: { id: string; name: string; strategy_type: string; version: number; status: string; coverage: Coverage; error: string | null }[]; limitations?: string[] }; deliveries?: { id: string; recipient: string; status: string; error: string | null }[] }
export interface Indicator { thresholds?: number[]; key: string; unit: string; pane: string; values: { time: string; value: number | null }[] }
export interface ChartSnapshot { report_id: string | null; scan_id: string; snapshot_id: string; instrument_id: number; symbol_as_of: string; market: string; session_timezone: string; price_semantics: string; as_of_session: string; available_from: string; available_to: string; next_cursor: string | null; bars: (CandleBarOut & { session_index?: number; price_source: Json })[]; indicator_series: Indicator[]; observation: Observation }
